- name: configure rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq-server
    ansible.builtin.dnf:
      name: rabbitmq
      state: installed

  - name: start ans enable rabbitmq-server
    ansible.builtin.service:
      name: rabbitmq
      state: started
      enabled: yes

  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present        